language: python

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

jobs:
  include:
    - stage: test
      script:
        - pytest
    - stage: deploy
      script:
        - pip install yolk3k
        - pip install twine
        - cd ci
        - python upload_package.py

stages:
  - test
  - deploy
