language: python
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest
after_success:
  - pip install yolk3k
  - pip install twine
  - cd ci
  - python upload_package.py
