# This workflow will create a pypi package and upload it with twine

name: Build

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-build.txt ]; then pip install -r requirements-build.txt; fi
    - name: Upload
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
      run: |
#        pip install yolk3k
#        pip install twine
#        pip install keyring==21.4.0
#        pip install wheel
        python ./setup.py sdist bdist_wheel
