# This workflow will create a pypi package and upload it with twine

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Upload
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install yolk3k
        pip install twine
        pip install keyring==21.4.0
        pip install wheel
        python ./setup.py sdist bdist_wheel
        ls
